=== bartek-jag/Studia/Projektowanie języków XML/lab5/zad1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="pracownik">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="imie" type="xsd:string"/>
				<xsd:element name="nazwisko" type="xsd:string"/>
				<xsd:element name="wiek" type="xsd:nonNegativeInteger"/>
				<xsd:element name="data_urodzenia" type="xsd:string"/>
				<xsd:element name="pensja" type="xsd:nonNegativeInteger"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

<!--
Zadanie 1. Stwórz plik XML-Schema zawierający deklarację elementów takich,
 że element główny o nazwie pracownik będzie zawierał elementy: imie, nazwisko, wiek, 
 data_urodzenia, pensja w podanej kolejności. Zastosuj odpowiedni typ danych.
Przetestuj działanie Schema na pliku XML.
-->

=== bartek-jag/Studia/Projektowanie języków XML/lab5/zad1.xml
<?xml version="1.0" encoding="UTF-8"?>
<pracownik xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="zad1.xsd">
	<imie>Bartosz</imie>
	<nazwisko>Jag≈Çowski</nazwisko>
	<wiek>10</wiek>
	<data_urodzenia>11.11.11<data_urodzenia>
	<pesja>15000<pensja>
</pracownik>
