=== bartek-jag/Studia/Projektowanie języków XML/lab7/zad4.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="firma">
    <xsd:complexType mixed="true">
      <xsd:sequence>
        <xsd:element name="produkt" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="nazwa" type="xsd:string"/>
              <xsd:element name="producent" type="xsd:string"/>
              <xsd:element name="cena" type="xsd:string"/>
            </xsd:sequence>
            <xsd:attribute name="id" type="xsd:string"/>
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="zakup" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="data_zakupu" type="xsd:string"/>
              <xsd:element name="ilosc" type="xsd:string"/>
            </xsd:sequence>
            <xsd:attribute name="id_produkt" type="xsd:string"/>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
    <xsd:unique name="u">
      <xsd:selector xpath="produkt"/>
      <xsd:field xpath="nazwa"/>
      <xsd:field xpath="producent"/>
    </xsd:unique>
    <xsd:key name="idProdukt">
      <xsd:selector xpath="produkt"/>
      <xsd:field xpath="@id"/>
    </xsd:key>
    <xsd:keyref name="refIdProdukt" refer="idProdukt">
      <xsd:selector xpath="zakup"/>
      <xsd:field xpath="@id_produkt"/>
    </xsd:keyref>
  </xsd:element>
</xsd:schema><!--
<xsd:keyref name="nazwa" refer="nazwa_klucza"> 
 <xsd:selector xpath="element/>
 <xsd:field xpath="wartość1/>
 <xsd:field xpath="wartość2/>

 <xsd:field xpath="wartośćN/>
</xsd:keyref>

Zadanie 4. Stwórz plik XML-Schema dla pliku XML. Struktura dokumentu.
Element główny firma
powinien zawierać element(y) o nazwie produkt w dowolnej ilości.
powinien zawierać element(y) o nazwie zakup w dowolnej ilości.
Element produkt
powinien zawierać jeden element o nazwie nazwa.
powinien zawierać jeden element o nazwie producent.
powinien zawierać jeden element o nazwie cena.
powinien zawierać atrybut o nazwie id.
dodatkowo elementy nazwa i producent (jednocześnie) powinny być unikatowe.

Element zakup
powinien zawierać jeden element o nazwie data_zakupu.
powinien zawierać jeden element o nazwie ilosc.
powinien zawierać atrybut o nazwie id_produkt.
dodatkowo elementy nazwa i producent (jednocześnie) powinny być unikatowe.
Element nazwa, producent, cena, data_zakupu, ilosc
powinny zawierać wartość tekstową wewnątrz.

Zastosuj odpowiedni typ danych do elementów i atrybutów. Skorzystaj z możliwości pobrania wartości klucza, aby przypisać wartość atrybutu id_produkt.
-->

=== bartek-jag/Studia/Projektowanie języków XML/lab7/zad4.xml
<?xml version='1.0' encoding='UTF-8'?>
<firma xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="zad4.xsd">
    <produkt id="a1">
        <nazwa>AA</nazwa>
        <producent>aB</producent>
        <cena>10</cena>
    </produkt>
    <produkt id="a2">
        <nazwa>AA</nazwa>
        <producent>AB</producent>
        <cena>10</cena>
    </produkt>
    <zakup id_produkt="a1">
        <data_zakupu>11</data_zakupu>
        <ilosc>11</ilosc>
    </zakup>
</firma>
